### ISSUE TITLE
Being able to alter hard disk size

### ISSUE THREAD

**Issue by rogierlommers** [mkuzmin/terraform-vsphere#16] opened 2015-02-12 14:54 UTC
It would be very useful is we could (optional) alter hard disk size. For example:

```
resource "vsphere_virtual_machine" "web" {
  name =  "bla"
  folder = "/linux"
  image = "/linux/dummy-vm"
  linked_clone = false
  cpus = 2
  memory = 4096
  power_on = false
  disk_size = 20480
}
```

**Comment by mkuzmin** [comment] 2015-02-12 15:06
A duplicate of https://github.com/mkuzmin/terraform-vsphere/issues/9

**Closed as completed** 2015-03-31 11:45 UTC
