### ISSUE TITLE
Ability to set a static IP address

### ISSUE THREAD

**Issue by nickithewatt** [mkuzmin/terraform-vsphere#20] opened 2015-04-06 16:31 UTC
Is it possible to set a static IP address? It looks like the ip_address config setting is only computed, which will work fine for DHCP type situations, but not for those needing to have static IPs assigned.

**Comment by mkuzmin** [comment] 2015-04-06 21:19
Hi

it seems a simple feature, please test a new build from https://github.com/mkuzmin/terraform-vsphere/releases/tag/v0.5.pre1
There are 3 new parameters you need to set: `ip_address`, `subnet_mask`, and `domain`.
The feature is based on #2, and has the same limitations: at the moment it works with Linux guests only, and supports just one network adapter.

I keep the issue open, and waiting for your feedback.

**Comment by nickithewatt** [comment] 2015-04-06 22:43
Hi and thanks for the prompt response!

I tried it out and appear to be getting the following error ...

```
. . .
* 1 error(s) occurred:

* Base image OS family is unknown
```

Its strange as it appears to work fine with the previous version. FYI the base image is Centos 7, and its vSphere 5.5.
WRT to the new parameters, perhaps there should also be a gateway parameter?

**Comment by mkuzmin** [comment] 2015-04-07 08:16
Do you have VMware tools installed inside a base VM you are cloning from?
That's a mandatory requirement for vSphere guest OS customization.

**Comment by mkuzmin** [comment] 2015-04-07 22:35
Hi 

I've added `gateway` parameter you requested, and also made a check for VMware Tools status.
Please test a new build from https://github.com/mkuzmin/terraform-vsphere/releases/tag/v0.5.pre2

**Comment by nickithewatt** [comment] 2015-04-08 09:38
Thanks Michael,
I believe vmtools are installed, but I shall give this a bash and let you know!

**Comment by nickithewatt** [comment] 2015-04-10 06:28
I have tested again and get a similar error - It doesn't seem top pickup the OS type for some reason.

```
* 1 error(s) occurred:
* Guest customization is supported only for Linux. Base image OS family is: 
```

vmtools are installed, I manually created a vm from the template and ran `vmware-toolbox-cmd -v` which resulted in `9.9.2.44151`

**Comment by mkuzmin** [comment] 2015-04-29 00:17
Finally, I was able to reproduce this issue. vSphere API is rather inconsistent here.
If you are still interested, try a new build from https://github.com/mkuzmin/terraform-vsphere/releases/v0.5.pre3

Per [VMware documentation](http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf) customization of CentOS 7 guests is supported in vSphere 6.0 only.
My vSphere 5.5 server raises this error:
 `Customization of the guest operating system 'centos64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.`

**Comment by nickithewatt** [comment] 2015-04-30 00:31
Thanks Michael,
I shall def have a look when I get a chance, been pulled onto some other work for now so it may take a bit of time.

**Comment by mkuzmin** [comment] 2015-06-15 22:10
I believe this feature is stable enough, so I close the issue.
Let me know if you meet any problems in future

**Closed as completed by mkuzmin** 2015-06-15 22:10 UTC

**Comment by fulloflilies** [comment] 2015-08-26 20:09
Hi,

I'm using Ubuntu14.04 for my guest OS and installed open-vm-tools.
Because VMware doesn't have VMware Tools for Ubuntu trusty yet and recommend to use open-vm-tools from the OS vendor. 
But when I run terraform apply the static IP doesn't seem to be set properly since I can't see IP addresses in the virtual machine summary and can't connect the IP manually. 

Would you be able to check if static IP can be set when open-vm-tools is installed instead of VMware tools?

**Comment by mkuzmin** [comment] 2015-08-27 19:00
Hi

Above I posted a link to VMware [Guest OS Customization Support Matrix](http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf). Ubuntu 14.04 is supported even in vSphere 5.1.

_open-vm-tools_ support basic VM guest interaction functionality, like graceful shutdown. But it does not provide features related to guest customization - renaming a host, setting static IP, and so on.
You have to download and install additional _DeployPkg_ package, as explained in http://kb.vmware.com/kb/2075048.

It may be easier to use native VMware tools provided with vSPhere client.

**Comment by fulloflilies** [comment] 2015-08-28 12:43
I'm using vCenter 5.5 and ESXi 5.5. 
When I try to install VMware Tools on guest Ubuntu14 by mounting CD Rom, I see VMwareTools-9.4.10-2068191.tar.gz is available. So I unzip and tried to install and got following message when I command ./vmware-install.pl in vmware-tools-distrib

open-vm-tools are available from the OS vendor and VMware recommends using open-vm-tools. See http://kb.vmware.com/kb/2073803 for more information.
Do you still want to proceed with this legacy installer? [no]

So I tried to see if there is VMware Tools to download from http://packages.vmware.com/tools/esx/index.html but couldn't find any package for Ubuntu Trusty on both ESXi 5.5 and 6.0. So it thought VMware doesn't support VMware tools for Ubuntu14 yet. 

However I could still install VMware tools from the legacy installer in CD rom since I also prefer to use native VMware tools and confirmed it creates VM with static IP set.

Thank you!
